<?php
/**
 * Copyright © Coduo. All rights reserved.
 * See COPYING.txt for license details.
 * http://www.coduo.cz | support@coduo.cz
 */

/** @var $block \Coduo\Core\Block\Adminhtml\Badge */
?>
<?php if ($block->isAuthorized()) : ?>
<script type="text/x-magento-init">
    {
        "*": {
            "coduoCoreNotificationIcon": {
                "url":"<?= $block->escapeUrl($block->getNotificationUrl()) ?>",
                "searchUrl":"<?= $block->escapeUrl($block->getSearchUrl()) ?>",
                "notificationOption": "<?= $block->getNotificationOption() ?>"
            }
        }
    }
</script>
<?php endif; ?>
